apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/kipsasjaujoj/demo-app
  newTag: 19bab76dcb218d6d18a53cf084327aa22ff80c01

resources:
- ../../base