apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/kipsasjaujoj/demo-app
  newTag: 6be7b81b330817fa28b2b9ea05427e54f70eb7cc

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: demo-app-dev
- target:
    kind: Service
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: demo-app-dev
